### PR TITLE
Swap name and tagname for grids

### PR DESCRIPTION
**Pull request by equinor-ruaj**
Solves (?) #101

### CODE REVIEW

**Comment by equinor-ruaj** [comment]
This probably also swaps `name <-> tagname` in `file.relative_path`...
Not sure if that breaks anything or will just "look weird" to users?

**Comment by rwiker** [comment]
The order in the filename should be the same as for other data types, I think.

**Comment by perolavsvendsen** [comment]
Agree that there should be consistency across data types and contents. But we also know that there isn't necessarily full consistency in the currently used standard which this tries to emulate. So probably not possible to 100% win.

If possible, we could try to produce a case or two with this update to `dev` and have a look. I think the data browser in the Sumo front-end will quickly reveal if this is more, or less, chaos.

**Comment by equinor-ruaj** [comment]
Separated metadata functions so "file.relative_path" should be set same as before. https://github.com/equinor/fmu-sumo-sim2sumo/pull/104/commits/b8c05cff37bc329100e2b81da2ea04128c7f39b2

**Comment by equinor-ruaj** [comment]
Uploaded two Drogon cases to `dev`.
Left: Using this branch
Right: Using Sim2sumo `main` branch
image

`name` and `tagname` is swapped as intended.
`file.relative_path` is the same in both.
The rest of the metadata is also the same in both cases.

Other datatypes are unchanged.

**Comment by equinor-ruaj** [comment]
Went through PR together with team offline 26.11.2024. Merging.

**Pull request merged**
